version: "3.9"

services:
  db:
    image: mongo:7.0.4-jammy
    volumes:
      - farm_stack_template_db:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: "app"
      MONGO_INITDB_USERNAME: "app"
      MONGO_INITDB_PASSWORD: "app"

volumes:
  farm_stack_template_db:
